INCLUDES = -Iapplication/include
INCLUDES += -Ilib/STM32F0xx_HAL_Driver/include 
INCLUDES += -Ilib/CMSIS/Device/ST/STM32F0xx/include
INCLUDES += -Ilib/CMSIS/include
INCLUDES += -ICore/include

#CFLAGS += -Wa,-adhln -g

obj-y = src/

export cmd_file := application/gcc_arm.ld