INCLUDES =  -Ilib/FreeRTOSv202210.01-LTS/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Kernel/include
INCLUDES += -Ilib/FreeRTOSv202210.01-LTS/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Kernel/portable/GCC/ARM_CM0
INCLUDES += -Iapplication/include

obj-y := FreeRTOS-LTS/FreeRTOS/FreeRTOS-Kernel/
obj-y += FreeRTOS-LTS/FreeRTOS/FreeRTOS-Kernel/portable/GCC/ARM_CM0/
obj-y += FreeRTOS-LTS/FreeRTOS/FreeRTOS-Kernel/portable/MemMang/

CFLAGS += -DconfigCPU_CLOCK_HZ=1000