
INCLUDES =  -Ilib/CMSIS/Device/ST/STM32F0xx/include
INCLUDES += -Ilib/CMSIS/include
INCLUDES += -ICore/include
INCLUDES += -Iapplication/include
INCLUDES += -Ilib/STM32F0xx_HAL_Driver/include


obj-y := src/