INCLUDES = -Iapplication/include
INCLUDES += -Ilib/STM32G4xx_HAL_Driver/include 
INCLUDES += -Ilib/CMSIS/Device/ST/STM32G4xx/include
INCLUDES += -Ilib/CMSIS/include
INCLUDES += -ICore/include
INCLUDES += -Iapplication/driver_model/include

#CFLAGS += -Wa,-adhln -g

obj-y = src/ driver_model/src/

export cmd_file := application/gcc_arm.ld