
// #include "stm32g4xx_hal_cortex.h"
// #include "stm32g4xx_hal_def.h"
// //#include "stm32g4xx_hal_dma_ex.h"
// //#include "stm32g4xx_hal_dma.h"
// #include "stm32g4xx_hal_exti.h"
// #include "stm32g4xx_hal_fdcan.h"
// //#include "stm32g4xx_hal_flash.h"
// //#include "stm32g4xx_hal_flash_ex.h"
// //#include "stm32g4xx_hal_flash_ramfunc.h"
// #include "stm32g4xx_hal_gpio_ex.h"
// #include "stm32g4xx_hal_gpio.h"
// #include "stm32g4xx_hal.h"
// #include "stm32g4xx_hal_pwr_ex.h"
// #include "stm32g4xx_hal_pwr.h"
// #include "stm32g4xx_hal_rcc.h"
// #include "stm32g4xx_hal_rcc_ex.h"
// #include "stm32g4xx_hal_spi_ex.h"
// #include "stm32g4xx_hal_spi.h"
// #include "stm32g4xx_hal_tim_ex.h"
// #include "stm32g4xx_hal_tim.h"
// //#include "stm32g4xx_hal_uart_ex.h"
// //#include "stm32g4xx_hal_uart.h"
#include "stm32g4xx.h"

